### ISSUE TITLE
Integration Failed

### ISSUE THREAD

**Issue by fiyors** [eelcohn/home-assistant-ddwrt#9] opened 2020-12-07 13:01 UTC
Hi Eelcohn, thanks for you work !

I cann´´t install the integration with HA 0.118.4 . what am I doing wrong ? 

Thanks

![image](https://user-images.githubusercontent.com/67486161/101353767-6eca5080-3894-11eb-82d7-82b09f7fa446.png)

`ogger: homeassistant.config_entries
Source: custom_components/ddwrt/pyddwrt.py:343
First occurred: 13:44:31 (3 occurrences)
Last logged: 13:55:34

Error setting up entry 192.168.27.2 for ddwrt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ddwrt/__init__.py", line 191, in async_setup_entry
    if not await router.async_update_sensor_data():
  File "/config/custom_components/ddwrt/__init__.py", line 382, in async_update_sensor_data
    result = await self._hass.async_add_executor_job(self._router.update_wireless_data)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ddwrt/pyddwrt.py", line 343, in update_wireless_data
    self.results.update({"wl_ack_distance": wl_ack.split("(")[1].split("m")[0]})
IndexError: list index out of range`

**Comment by eelcohn** [comment] 2020-12-08 08:31
You're not doing anything wrong, this problem is caused by the many, many different versions of DD-WRT. Aparently the value of `wl_ack_distance` in the `/Status_Wireless.live.asp` is a bit different than the devices I've used for testing.

Can you open `http://192.168.27.2/Status_Wireless.live.asp` in your browser, and post the result here? Please remove/change any sensitive data (like passwords / wireless access point names) before you post it!

**Comment by fiyors** [comment] 2020-12-08 09:02
Good morning Eelcohn !

This is the result !

{wl_mac::xx:xx:xx:xx:xx:xx }{wl_ssid:: SSIDXXX }{wl_channel::desconocido}{wl_radio::El adaptador está apagado}{wl_xmit::El adaptador está apagado}{wl_rate::Desactivado}{wl_busy::}{wl_active::}{wl_quality::}{wl_ack::N/A}{active_wireless::}{active_wds::}{packet_info::SWRXgoodPacket=0;SWRXerrorPacket=0;SWTXgoodPacket=0;SWTXerrorPacket=0;}{uptime:: 09:57:27 up 3 min, load average: 0.04, 0.05, 0.01}{ipinfo:: IP: 192.168.1.3}

![image](https://user-images.githubusercontent.com/67486161/101462334-69284580-393c-11eb-9d7b-920ba40473de.png)

The parameters that only i need is : Total Traffic, temperature , RX and TX.  The wifi is administrate by unify !

Thanks Again !

**Comment by eelcohn** [comment] 2020-12-08 22:32
Thanks for the info. I've pushed [v1.1.2](https://github.com/eelcohn/home-assistant-ddwrt/tree/v1.1.2) to the repository. Can you try [this branch](https://github.com/eelcohn/home-assistant-ddwrt/tree/v1.1.2) and see if it fixes your problem?

**Comment by fiyors** [comment] 2020-12-09 16:18
Hi Eelcohn. I just tried via Yaml and lovelace, with the LAN IP and WAN ip and doesn´t work. 

{wl_mac::xxxxxxx}{wl_ssid::-xxxxxxx }{wl_channel::desconocido}{wl_radio::El adaptador está apagado}{wl_xmit::El adaptador está apagado}{wl_rate::Desactivado}{wl_busy::}{wl_active::}{wl_quality::}{wl_ack::N/A}{active_wireless::}{active_wds::}{packet_info::SWRXgoodPacket=0;SWRXerrorPacket=0;SWTXgoodPacket=0;SWTXerrorPacket=0;}{uptime:: 17:17:20 up 1 day, 7:23, load average: 0.00, 0.00, 0.00}{ipinfo:: IP: 192.168.1.3}

Thanks anyway.

**Comment by BeerDiet** [comment] 2020-12-23 14:33
Hi Eelcohn!  Treating the "N/A" in the string worked for me.

**Comment by eelcohn** [comment] 2021-06-04 14:15
Should be fixed with v1.1.2

**Closed as completed by eelcohn** 2021-06-04 14:15 UTC
